### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by cristianvogel** [untemps/svelte-use-tooltip#32]
Hi

Only cutting and pasting your demo component code into my Svelte project, then trying to view it on a page as a route. But I get this all the time.

`The requested module '/node_modules/@untemps/svelte-use-tooltip/dist/index.js' does not provide an export named 'useTooltip'`

**Comment by untemps** [comment]
Hi,
Can you give me some clues about your stack and a sample of your code where you import the lib?

**Comment by untemps** [comment]
Fixed by pointing svelte entry to esm distribution.
